# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-23 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_restapi', '0006_auto_20210223_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='user',
        ),
    ]
